<a href="https://colab.research.google.com/github/AnastasiiaDm/machine-learning/blob/main/DZ_2_numpy_pandas/hw_pandas_ukr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<img src="../../img/ods_stickers.jpg">
## Открытый курс по машинному обучению
<center>
Автор материала: Юрий Кашницкий, программист-исследователь Mail.Ru Group <br>

Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

# <center>Домашнє завдання № 1 (демо).<br> Аналіз даних доходів населення UCI Adult</center>

**В завданні пропонується за допомогою Pandas дати відповідь на кілька запитань по даним репозиторія UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult).**

Унікальні значення ознак:
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K



```
# Выбран кодовый формат
```

**1. Скільки чоловіків и жінок (ознака *sex*) представлено в цьому наборі даних?**

In [5]:
# dataframe version:
# gender_counts = data["sex"].value_counts()

female_amount = len(data[data["sex"] == "Female"])
male_amount = len(data[data["sex"] == "Male"])
print(f"Female amount: {female_amount}")
print(f"Male amount: {male_amount}")

Female amount: 10771
Male amount: 21790

**2. Який середній вік (ознака *age*) жінок?**

In [6]:
average_age_female = data[data["sex"] == "Female"]["age"].mean()
print(f'Average female age: {average_age_female}')

Average female age: 36.85823043357163

**3. Яка доля громадян Німеччини (ознака *native-country*)?**

In [7]:
germany_native_count = len(data[data["native-country"] == "Germany"])
germany_native_ratio = germany_native_count / len(data)
print(f'Germany native ratio: {germany_native_ratio}')

Germany native ratio: 0.004207487485028101

**4-5. Які средні значення та средньоквадратичні відхилення віку тих, хто отримує більше 50K на рік (ознака *salary*) і тих, хто отримує менше 50K на рік?**

In [8]:
# dataframe version:
# age_stats = data.groupby("salary")["age"].agg(["mean", "std"])
high_income = data[data["salary"] == ">50K"]
low_income = data[data["salary"] == "<=50K"]

mean_high = high_income["age"].mean()
std_high = high_income["age"].std()

mean_low = low_income["age"].mean()
std_low = low_income["age"].std()
print(f"Those earning >50K: average age = {mean_high}, standard deviation = {std_high}")
print(f"Those earning <=50K: average age = {mean_low}, standard deviation = {std_low}")

Those earning >50K: average age = 44.24984058155847, standard deviation = 10.51902771985177
Those earning <=50K: average age = 36.78373786407767, standard deviation = 14.020088490824813

**6. Чи правда, що люди, які отримують більше 50k, мають як мінімум вищу освіту? (ознака *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [9]:
higher_education = ["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters", "Doctorate"]
has_higher_education = high_income["education"].isin(higher_education)

if has_higher_education.all():
    print("True, all people earning >50K have at least higher education.")
else:
    print("False, not all people earning >50K have higher education.")

False, not all people earning >50K have higher education.

**7. Порахуйте статистику віку для кожної раси (ознака *race*) і кожної статі. Використайте *groupby* и *describe*. Знайдіть таким сином максимальний вік чоловіків раси *Amer-Indian-Eskimo*.**

In [10]:
age_stats = data.groupby(["race", "sex"])["age"].describe()

max_age_amer_indian_eskimo_male = data[(data["race"] == "Amer-Indian-Eskimo") & (data["sex"] == "Male")]["age"].max()
print(f'Max age of Amer-Indian-Eskimo males: {max_age_amer_indian_eskimo_male}')

Max age of Amer-Indian-Eskimo males: 82

**8. Серед кого більша доля багатіших (>50K): серед одружених чи не одружених чоловіків (ознака *marital-status*)? За одружених вважаємо тих, у кого *marital-status* починається із *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), всі інші - не одружені.**

In [47]:
men = data[data["sex"] == "Male"]

married_statuses = ["Married-civ-spouse", "Married-spouse-absent", "Married-AF-spouse"]
is_married = men["marital-status"].isin(married_statuses)

married_men_rich_ratio = (men[is_married]["salary"].eq(">50K")).shape[0] / men.shape[0]
unmarried_men_rich_ratio = (men[~is_married]["salary"].eq(">50K")).shape[0] / men.shape[0]

if married_men_rich_ratio > unmarried_men_rich_ratio:
  print(f'Married rich men ratio {married_rich_ratio} is more than unmarried rich men ratio {unmarried_rich_ratio}')
else:
  print(f'Unmarried rich men ratio {unmarried_rich_ratio} is more than married rich men ratio {married_rich_ratio}')

Married rich men ratio 0.621431849472235 is more than unmarried rich men ratio 0.08449509031397745

**9. Яку максимальну кількість годин в тиждень працює людина (ознака *hours-per-week*)? Скільки людей працюють таку кількість годин і який відсоток серед них багатих?**

In [49]:
max_hours = data["hours-per-week"].max()
num_people_max_hours = data[data["hours-per-week"] == max_hours].shape[0]
rich_ratio = data[(data["hours-per-week"] == max_hours) & (data["salary"] == ">50K")].shape[0] / num_people_max_hours

print(f"Maximum number of hours worked per week: {max_hours}")
print(f"Number of people working maximum hours: {num_people_max_hours}")
print(f"Percentage of reach people: {rich_ratio:.2%}")

Maximum number of hours worked per week: 99
Number of people working maximum hours: 85
Percentage of reach people: 29.41%

**10. Порахуйте середню тривалість роботи на тиждень (*hours-per-week*) серед багатих і бідних (*salary*) для кожної країни (*native-country*).**

In [53]:
# mean_hours_weekly_rich = data[data["salary"] == ">50K"]
avg_work_hours = data.groupby(["native-country", "salary"])["hours-per-week"].mean().unstack()
avg_work_hours

salary                          <=50K       >50K
native-country
?                           40.164760  45.547945
Cambodia                    41.416667  40.000000
Canada                      37.914634  45.641026
China                       37.381818  38.900000
Columbia                    38.684211  50.000000
Cuba                        37.985714  42.440000
Dominican-Republic          42.338235  47.000000
Ecuador                     38.041667  48.750000
El-Salvador                 36.030928  45.000000
England                     40.483333  44.533333
France                      41.058824  50.750000
Germany                     39.139785  44.977273
Greece                      41.809524  50.625000
Guatemala                   39.360656  36.666667
Haiti                       36.325000  42.750000
Holand-Netherlands          40.000000        NaN
Honduras                    34.333333  60.000000
Hong                        39.142857  45.000000
Hungary                     31.300000  50.000000
India                       38.233333  46.475000
Iran                        41.440000  47.500000
Ireland                     40.947368  48.000000
Italy                       39.625000  45.400000
Jamaica                     38.239437  41.100000
Japan                       41.000000  47.958333
Laos                        40.375000  40.000000
Mexico                      40.003279  46.575758
Nicaragua                   36.093750  37.500000
Outlying-US(Guam-USVI-etc)  41.857143        NaN
Peru                        35.068966  40.000000
Philippines                 38.065693  43.032787
Poland                      38.166667  39.000000
Portugal                    41.939394  41.500000
Puerto-Rico                 38.470588  39.416667
Scotland                    39.444444  46.666667
South                       40.156250  51.437500
Taiwan                      33.774194  46.800000
Thailand                    42.866667  58.333333
Trinadad&Tobago             37.058824  40.000000
United-States               38.799127  45.505369
Vietnam                     37.193548  39.200000
Yugoslavia                  41.600000  49.500000